config/routes.rb
Rails.application.routes.draw do
  get "city/index"
  get "city/cities"
  get "country/provinces", to: "country#provinces", as: :country_provinces
  get "province/cities", to: "province#cities", as: :province_cities
  get "province/index", to: "province#index", as: :province_index

  resources :provinces, only: [ :index ]
  resources :cities, only: [ :index ]

  get "home/index"

  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

   root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :province
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :provinces, dependent: :destroy
end

app/models/province.rb
class Province < ApplicationRecord
  belongs_to :country
  has_many :cities, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def index
    @cities = City.where(province_id: params[:province_id])
    respond_to do |format|
      format.html
      format.json { render json: @cities.select(:id, :name_city) }
    end
  end

  def create
    @city = City.new(city_params)
    if @city.save
      redirect_to city_index_path(province_id: @city.province_id), notice: "City was successfully created."
    else
      render :cities
    end
  end

  private
  def city_params
    params.require(:city).permit(:name_city, :province_id)
  end
end

app/controllers/city_controller.rb
class CitiesController < ApplicationController
  def index
    @cities = City.where(province_id: params[:province_id])
    respond_to do |format|
      format.html
      format.json { render json: @cities.select(:id, :name_city) }
    end
  end

  def create
    @city = City.new(city_params)
    if @city.save
      redirect_to city_index_path(province_id: @city.province_id), notice: "City was successfully created."
    else
      render :cities
    end
  end

  private
  def city_params
    params.require(:city).permit(:name_city, :province_id)
  end
end

app/controllers/country_controller.rb
class CountryController < ApplicationController
  def provinces
    @provinces = Province.where(country_id: params[:country_id])
    render partial: "province/province_select", locals: { provinces: @provinces }
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/province_controller.rb
class ProvincesController < ApplicationController
  def index
    @provinces = Province.where(country_id: params[:country_id])
    respond_to do |format|
      format.html
      format.json { render json: @provinces.select(:id, :name_province) }
    end
  end

  def cities
    @province_id = params[:province_id]
    @city = City.new
    render partial: "city/city_select", locals: { province_id: @province_id, city: @city }
  end
end

app/controllers/provinces_controller.rb
class ProvincesController < ApplicationController
  def index
    @provinces = Province.where(country_id: params[:country_id])
    respond_to do |format|
      format.html
      format.json { render json: @provinces.select(:id, :name_province) }
    end
  end

  def cities
    @province_id = params[:province_id]
    @city = City.new
    render partial: "city/city_select", locals: { province_id: @province_id, city: @city }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/country_helper.rb
module CountryHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/province_helper.rb
module ProvinceHelper
end

app/views/city/_city_select.html.erb
<%= form_with model: city, url: city_index_path, method: :post do |form| %>
  <%= form.label :name_city, "City Name" %>
  <%= form.text_field :name_city %>
  <%= form.hidden_field :province_id, value: province_id %>
  <%= form.submit "Create City" %>
<% end %>

app/views/city/cities.html.erb
CITY HAS BEEN CREATE SUCCESS FULY

app/views/city/index.html.erb
<h1>City#index</h1>
<p>Find me in app/views/city/index.html.erb</p>

<%= form_with model: @city do |form| %>
  <%= form.select :province_id, @cities.collect { |p| [p.name_city, p.id] }, { prompt: "Choose a province" } %>
  <%= form.submit "Create City" %>
<% end %>

app/views/country/provinces.html.erb
<h1>Country#provinces</h1>
<p>Find me in app/views/country/provinces.html.erb</p>

app/views/home/index.html.erb
<h1>Single Page Selects</h1>

<form id="location-form">
  <label for="country-select">Country:</label>
  <select id="country-select" name="country_id">
    <option value="">Choose a country</option>
    <% Country.all.each do |country| %>
      <option value="<%= country.id %>"><%= country.name_country %></option>
    <% end %>
  </select>

  <label for="province-select">Province:</label>
  <select id="province-select" name="province_id" disabled>
    <option value="">Choose a province</option>
  </select>

  <label for="city-select">City:</label>
  <select id="city-select" name="city_id" disabled>
    <option value="">Choose a city</option>
  </select>
</form>

<script>
document.addEventListener('DOMContentLoaded', function() {
  const countrySelect = document.getElementById('country-select');
  const provinceSelect = document.getElementById('province-select');
  const citySelect = document.getElementById('city-select');

  countrySelect.addEventListener('change', function() {
    const countryId = this.value;
    provinceSelect.innerHTML = '<option value="">Choose a province</option>';
    citySelect.innerHTML = '<option value="">Choose a city</option>';
    citySelect.disabled = true;
    if (countryId) {
      fetch(`/provinces.json?country_id=${countryId}`)
        .then(response => response.json())
        .then(data => {
          provinceSelect.disabled = false;
          data.forEach(function(province) {
            const option = document.createElement('option');
            option.value = province.id;
            option.textContent = province.name_province;
            provinceSelect.appendChild(option);
          });
        });
    } else {
      provinceSelect.disabled = true;
    }
  });

  provinceSelect.addEventListener('change', function() {
    const provinceId = this.value;
    citySelect.innerHTML = '<option value="">Choose a city</option>';
    if (provinceId) {
      fetch(`/cities.json?province_id=${provinceId}`)
        .then(response => response.json())
        .then(data => {
          citySelect.disabled = false;
          data.forEach(function(city) {
            const option = document.createElement('option');
            option.value = city.id;
            option.textContent = city.name_city;
            citySelect.appendChild(option);
          });
        });
    } else {
      citySelect.disabled = true;
    }
  });
});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Dependent Select" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/province/_province_select.html.erb
<%= form_with url: province_cities_path, method: :get, data: { turbo_frame: "city_select" } do |form| %>
  <%= form.label :province_id, "Select Province" %>
  <%= form.collection_select :province_id, provinces, :id, :name_province, { prompt: "Choose a province" } %>
<% end %>

app/views/province/index.html.erb
<h1>Province#index</h1>
<p>Find me in app/views/province/index.html.erb</p>

<%= form_with url: province_cities_path, method: :get, local: true, html: { id: "country-form" } do |form| %>
  <%= form.label :province_id, "Select province" %>
  <%= form.collection_select :province_id, @provinces, :id, :name_province, { prompt: "Choose a province" }, { onchange: "this.form.submit();" } %>
<% end %>